apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: framework
  name: framework
  namespace: default
spec:
  replicas: 10
  selector:
    name: framework
  template:
    metadata:
      labels:
        cagby.io/color: 4C9900
        name: framework
    spec:
      containers:
      - image: 172.16.16.15:5000/trogdor-framework:latest
        imagePullPolicy: Always
        name: framework
        ports:
        - containerPort: 9080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        region: zone3
