apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: InfluxDB
    kubernetes.io/cluster-service: "true"
    version: v1
  name: influxdb-v1
  namespace: default
spec:
  replicas: 1
  selector:
    k8s-app: InfluxDB
    version: v1
  template:
    metadata:
      labels:
        k8s-app: InfluxDB
        kubernetes.io/color: 6666FF
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - env:
        - name: INFLUXDB_INIT_PWD
          value: root
        - name: PRE_CREATE_DB
          value: k8s;grafana
        image: quay.io/samsung_ag/influxdb:latest
        imagePullPolicy: Always
        name: influxdb
        ports:
        - containerPort: 8083
          hostPort: 8083
          protocol: TCP
        - containerPort: 8086
          hostPort: 8086
          protocol: TCP
      dnsPolicy: ClusterFirst
      nodeSelector:
        kraken-node: node-001
      restartPolicy: Always
