apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: pause
  name: pause
  namespace: default
spec:
  replicas: 10
  selector:
    name: pause
  template:
    metadata:
      labels:
        name: pause
        kubernetes.io/color: "444444"
    spec:
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:go
      dnsPolicy: ClusterFirst
      restartPolicy: Always
