apiVersion: v1
kind: Service
metadata:
  labels:
    name: pause
    kubernetes.io/name: "Pause"
  name: pause
  namespace: default
spec:
  ports:
  - name: pause
    port: 80
  selector:
    name: pause
  sessionAffinity: None
  type: ClusterIP
